<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "resa_unal"
 *
 * Auto generated by Extension Builder 2018-01-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RESA Unal',
    'description' => 'This extension allows the user to manage a series of publications managed via Fusion Tables',
    'category' => 'plugin',
    'author' => 'Alexis Ortiz ',
    'author_email' => 'eaortiz@unal.edu.co',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
